import type {
  CanvasObject,
  CanvasObjectMeta,
  CanvasObjectType,
  LayoutJsonDocument,
} from "@/types/layout";

const GOLD = "#fbbf24";
const WOOD = "#d4a574";
const LINEN = "#ffedd5";
const GREEN = "#86efac";
const SLATE = "#64748b";

export function emptyLayoutDocument(): LayoutJsonDocument {
  return { version: 1, objects: [] };
}

function obj(
  partial: Omit<CanvasObject, "id" | "meta"> & {
    id?: string;
    meta?: CanvasObjectMeta;
  },
): CanvasObject {
  return {
    id: partial.id ?? crypto.randomUUID(),
    ...partial,
    meta: partial.meta ?? {},
  };
}

/**
 * Sample ballroom reception (cool-climate / garden-resort style): stage, dance floor,
 * sweetheart table, guest rounds, buffet, registration, and flow labels.
 * Laid out on a 1520×960 canvas with generous gutters so captions and zones do not overlap.
 */
export function getBccSampleLayoutObjects(): CanvasObject[] {
  return [
    obj({
      type: "text_label",
      x: 120,
      y: 20,
      width: 1280,
      height: 48,
      rotation: 0,
      label: "Grand ballroom — sample floor plan (drag items to match your venue)",
      color: "#3d3a36",
      meta: {},
    }),
    obj({
      type: "buffet_table",
      x: 48,
      y: 104,
      width: 268,
      height: 54,
      rotation: 0,
      label: "Buffet line",
      color: WOOD,
      meta: { notes: "Regional cold & warm stations — lechon carving optional" },
    }),
    obj({
      type: "dessert_table",
      x: 328,
      y: 104,
      width: 132,
      height: 54,
      rotation: 0,
      label: "Dessert",
      color: LINEN,
    }),
    obj({
      type: "stage",
      x: 520,
      y: 100,
      width: 440,
      height: 92,
      rotation: 0,
      label: "Stage & backdrop",
      color: SLATE,
      meta: { notes: "Garden-view side — evergreen and fern backdrop" },
    }),
    obj({
      type: "projector_screen",
      x: 600,
      y: 104,
      width: 280,
      height: 32,
      rotation: 0,
      label: "Screen",
      color: "#222",
    }),
    obj({
      type: "reserved_area",
      x: 1000,
      y: 88,
      width: 200,
      height: 72,
      rotation: 0,
      label: "Reserved cordon",
      color: "#c9b8a0",
      meta: { notes: "Cool evening air — shawls basket by the door" },
    }),
    obj({
      type: "registration_table",
      x: 1220,
      y: 88,
      width: 190,
      height: 54,
      rotation: 0,
      label: "Registration",
      color: LINEN,
      meta: { seatCount: 2 },
    }),
    obj({
      type: "gift_table",
      x: 1220,
      y: 228,
      width: 190,
      height: 52,
      rotation: 0,
      label: "Gifts",
      color: LINEN,
    }),
    obj({
      type: "ceremony_arch",
      x: 48,
      y: 248,
      width: 148,
      height: 72,
      rotation: 0,
      label: "Feature florals",
      color: GREEN,
    }),
    obj({
      type: "speaker",
      x: 468,
      y: 206,
      width: 40,
      height: 40,
      rotation: 0,
      label: "L",
      color: "#333",
    }),
    obj({
      type: "speaker",
      x: 972,
      y: 206,
      width: 40,
      height: 40,
      rotation: 0,
      label: "R",
      color: "#333",
    }),
    obj({
      type: "sweetheart_table",
      x: 700,
      y: 244,
      width: 120,
      height: 56,
      rotation: 0,
      label: "Sweetheart",
      color: GOLD,
      meta: { seatCount: 2, guestNames: ["Couple"] },
    }),
    obj({
      type: "dance_floor",
      x: 500,
      y: 372,
      width: 520,
      height: 280,
      rotation: 0,
      label: "Dance floor",
      color: "#d8cfc0",
      meta: {},
    }),
    obj({
      type: "aisle",
      x: 420,
      y: 388,
      width: 44,
      height: 264,
      rotation: 0,
      label: "Side aisle",
      color: "#e8e2d8",
    }),
    obj({
      type: "round_table",
      x: 100,
      y: 396,
      width: 96,
      height: 96,
      rotation: 0,
      label: "Table 1",
      color: LINEN,
      meta: { seatCount: 8, guestNames: [] },
    }),
    obj({
      type: "round_table",
      x: 100,
      y: 584,
      width: 96,
      height: 96,
      rotation: 0,
      label: "Table 2",
      color: LINEN,
      meta: { seatCount: 8, guestNames: [] },
    }),
    obj({
      type: "round_table",
      x: 100,
      y: 772,
      width: 96,
      height: 96,
      rotation: 0,
      label: "Table 3",
      color: LINEN,
      meta: { seatCount: 8, guestNames: [] },
    }),
    obj({
      type: "round_table",
      x: 1324,
      y: 396,
      width: 96,
      height: 96,
      rotation: 0,
      label: "Table 4",
      color: LINEN,
      meta: { seatCount: 8, guestNames: [] },
    }),
    obj({
      type: "round_table",
      x: 1324,
      y: 584,
      width: 96,
      height: 96,
      rotation: 0,
      label: "Table 5",
      color: LINEN,
      meta: { seatCount: 8, guestNames: [] },
    }),
    obj({
      type: "round_table",
      x: 1324,
      y: 772,
      width: 96,
      height: 96,
      rotation: 0,
      label: "Table 6",
      color: LINEN,
      meta: { seatCount: 8, guestNames: [] },
    }),
    obj({
      type: "rectangular_table",
      x: 56,
      y: 976,
      width: 310,
      height: 58,
      rotation: 0,
      label: "VIP family",
      color: LINEN,
      meta: { seatCount: 10, guestNames: [] },
    }),
    obj({
      type: "bar_area",
      x: 394,
      y: 976,
      width: 280,
      height: 58,
      rotation: 0,
      label: "Bar",
      color: WOOD,
      meta: { seatCount: 4 },
    }),
    obj({
      type: "lounge_sofa",
      x: 702,
      y: 976,
      width: 330,
      height: 58,
      rotation: 0,
      label: "Lounge",
      color: "#6d5b4c",
    }),
    obj({
      type: "photo_booth",
      x: 1060,
      y: 976,
      width: 404,
      height: 58,
      rotation: 0,
      label: "Photo booth",
      color: "#6a5acd",
    }),
    obj({
      type: "entrance",
      x: 500,
      y: 684,
      width: 128,
      height: 52,
      rotation: 0,
      label: "Entrance",
      color: GREEN,
    }),
    obj({
      type: "exit",
      x: 820,
      y: 684,
      width: 128,
      height: 52,
      rotation: 0,
      label: "Exit (lawn)",
      color: GREEN,
    }),
    obj({
      type: "flower_stand",
      x: 312,
      y: 492,
      width: 36,
      height: 36,
      rotation: 0,
      label: "",
      color: GREEN,
    }),
    obj({
      type: "flower_stand",
      x: 1172,
      y: 492,
      width: 36,
      height: 36,
      rotation: 0,
      label: "",
      color: GREEN,
    }),
    obj({
      type: "plant_decor",
      x: 360,
      y: 668,
      width: 32,
      height: 32,
      rotation: 0,
      label: "",
      color: GREEN,
    }),
  ];
}

export function bccSampleDocument(): LayoutJsonDocument {
  return {
    version: 1,
    objects: getBccSampleLayoutObjects(),
  };
}

/** Ceremony starter: nave aisle, arch, pews, and guest chairs. */
export function getChurchSampleLayoutObjects(): CanvasObject[] {
  return [
    obj({
      type: "text_label",
      x: 200,
      y: 28,
      width: 500,
      height: 52,
      rotation: 0,
      label: "Church ceremony — top view (resize canvas & drag items to fit your nave)",
      color: "#2e2a26",
      meta: {},
    }),
    obj({
      type: "ceremony_arch",
      x: 360,
      y: 92,
      width: 180,
      height: 72,
      rotation: 0,
      label: "Wedding arch",
      color: GREEN,
    }),
    obj({
      type: "aisle",
      x: 426,
      y: 180,
      width: 48,
      height: 820,
      rotation: 0,
      label: "Center aisle",
      color: "#e8e2d8",
    }),
    obj({
      type: "church_pew",
      x: 72,
      y: 200,
      width: 300,
      height: 32,
      rotation: 0,
      label: "Pew — left",
      color: WOOD,
    }),
    obj({
      type: "church_pew",
      x: 72,
      y: 320,
      width: 300,
      height: 32,
      rotation: 0,
      label: "Pew",
      color: WOOD,
    }),
    obj({
      type: "church_pew",
      x: 72,
      y: 440,
      width: 300,
      height: 32,
      rotation: 0,
      label: "Pew",
      color: WOOD,
    }),
    obj({
      type: "church_pew",
      x: 528,
      y: 200,
      width: 300,
      height: 32,
      rotation: 0,
      label: "Pew — right",
      color: WOOD,
    }),
    obj({
      type: "church_pew",
      x: 528,
      y: 320,
      width: 300,
      height: 32,
      rotation: 0,
      label: "Pew",
      color: WOOD,
    }),
    obj({
      type: "church_pew",
      x: 528,
      y: 440,
      width: 300,
      height: 32,
      rotation: 0,
      label: "Pew",
      color: WOOD,
    }),
    obj({
      type: "chair",
      x: 200,
      y: 260,
      width: 28,
      height: 28,
      rotation: 0,
      label: "",
      color: WOOD,
    }),
    obj({
      type: "chair",
      x: 240,
      y: 260,
      width: 28,
      height: 28,
      rotation: 0,
      label: "",
      color: WOOD,
    }),
    obj({
      type: "chair",
      x: 632,
      y: 260,
      width: 28,
      height: 28,
      rotation: 0,
      label: "",
      color: WOOD,
    }),
    obj({
      type: "chair",
      x: 672,
      y: 260,
      width: 28,
      height: 28,
      rotation: 0,
      label: "",
      color: WOOD,
    }),
    obj({
      type: "speaker",
      x: 120,
      y: 120,
      width: 36,
      height: 36,
      rotation: 0,
      label: "L",
      color: "#475569",
    }),
    obj({
      type: "speaker",
      x: 744,
      y: 120,
      width: 36,
      height: 36,
      rotation: 0,
      label: "R",
      color: "#475569",
    }),
    obj({
      type: "entrance",
      x: 380,
      y: 1180,
      width: 140,
      height: 48,
      rotation: 0,
      label: "Narthex / doors",
      color: GREEN,
    }),
  ];
}

export function churchSampleDocument(): LayoutJsonDocument {
  return { version: 1, objects: getChurchSampleLayoutObjects() };
}

/** Garden / tented reception starter. */
export function getGardenSampleLayoutObjects(): CanvasObject[] {
  return [
    obj({
      type: "text_label",
      x: 120,
      y: 20,
      width: 720,
      height: 28,
      rotation: 0,
      label: "Outdoor garden — tent, lawn dance floor, and arbor (resize page as needed)",
      color: "#2e2a26",
      meta: {},
    }),
    obj({
      type: "outdoor_tent",
      x: 80,
      y: 80,
      width: 360,
      height: 220,
      rotation: 0,
      label: "Reception tent",
      color: "#fef3c7",
      meta: { notes: "Sailcloth / frame tent — adjust footprint to vendor specs" },
    }),
    obj({
      type: "dance_floor",
      x: 520,
      y: 200,
      width: 380,
      height: 280,
      rotation: 0,
      label: "Lawn dance floor",
      color: "#d8cfc0",
    }),
    obj({
      type: "garden_arbor",
      x: 1040,
      y: 160,
      width: 140,
      height: 120,
      rotation: 0,
      label: "Garden arbor",
      color: "#86efac",
    }),
    obj({
      type: "ceremony_arch",
      x: 1240,
      y: 120,
      width: 120,
      height: 64,
      rotation: 0,
      label: "Ceremony arch",
      color: GREEN,
    }),
    obj({
      type: "round_table",
      x: 160,
      y: 360,
      width: 88,
      height: 88,
      rotation: 0,
      label: "Cocktail 1",
      color: LINEN,
      meta: { seatCount: 6, guestNames: [] },
    }),
    obj({
      type: "round_table",
      x: 280,
      y: 360,
      width: 88,
      height: 88,
      rotation: 0,
      label: "Cocktail 2",
      color: LINEN,
      meta: { seatCount: 6, guestNames: [] },
    }),
    obj({
      type: "bar_area",
      x: 480,
      y: 520,
      width: 180,
      height: 72,
      rotation: 0,
      label: "Outdoor bar",
      color: WOOD,
    }),
    obj({
      type: "plant_decor",
      x: 60,
      y: 520,
      width: 40,
      height: 40,
      rotation: 0,
      label: "",
      color: GREEN,
    }),
    obj({
      type: "plant_decor",
      x: 1320,
      y: 420,
      width: 40,
      height: 40,
      rotation: 0,
      label: "",
      color: GREEN,
    }),
    obj({
      type: "flower_stand",
      x: 980,
      y: 360,
      width: 36,
      height: 36,
      rotation: 0,
      label: "",
      color: GREEN,
    }),
    obj({
      type: "flower_stand",
      x: 1140,
      y: 360,
      width: 36,
      height: 36,
      rotation: 0,
      label: "",
      color: GREEN,
    }),
    obj({
      type: "entrance",
      x: 720,
      y: 820,
      width: 160,
      height: 52,
      rotation: 0,
      label: "Garden entrance",
      color: GREEN,
    }),
    obj({
      type: "reserved_area",
      x: 1220,
      y: 520,
      width: 200,
      height: 100,
      rotation: 0,
      label: "Vendor / generator",
      color: "#c9b8a0",
    }),
  ];
}

export function gardenSampleDocument(): LayoutJsonDocument {
  return { version: 1, objects: getGardenSampleLayoutObjects() };
}

export const DEFAULT_CANVAS_WIDTH = 1520;
export const DEFAULT_CANVAS_HEIGHT = 1120;

export function defaultObjectForType(type: CanvasObjectType): Omit<
  CanvasObject,
  "id"
> {
  const defaults: Record<
    CanvasObjectType,
    { w: number; h: number; color: string; label: string }
  > = {
    round_table: { w: 88, h: 88, color: LINEN, label: "Round table" },
    rectangular_table: { w: 160, h: 72, color: LINEN, label: "Banquet table" },
    chair: { w: 28, h: 28, color: WOOD, label: "" },
    sweetheart_table: { w: 200, h: 104, color: GOLD, label: "Sweetheart" },
    stage: { w: 320, h: 96, color: SLATE, label: "Stage" },
    dance_floor: { w: 240, h: 200, color: "#d8cfc0", label: "Dance floor" },
    entrance: { w: 72, h: 40, color: GREEN, label: "Entrance" },
    exit: { w: 72, h: 40, color: GREEN, label: "Exit" },
    buffet_table: { w: 200, h: 56, color: WOOD, label: "Buffet" },
    dessert_table: { w: 120, h: 48, color: LINEN, label: "Dessert" },
    registration_table: { w: 140, h: 56, color: LINEN, label: "Registration" },
    photo_booth: { w: 100, h: 72, color: "#c4b5fd", label: "Photo booth" },
    aisle: { w: 48, h: 200, color: "#e8e2d8", label: "Aisle" },
    ceremony_arch: { w: 140, h: 64, color: GREEN, label: "Arch" },
    flower_stand: { w: 32, h: 32, color: GREEN, label: "" },
    speaker: { w: 36, h: 36, color: "#94a3b8", label: "Speaker" },
    projector_screen: { w: 220, h: 28, color: "#cbd5e1", label: "Screen" },
    bar_area: { w: 140, h: 64, color: WOOD, label: "Bar" },
    gift_table: { w: 96, h: 48, color: LINEN, label: "Gifts" },
    lounge_sofa: { w: 180, h: 64, color: "#c4b5fd", label: "Lounge" },
    plant_decor: { w: 32, h: 32, color: GREEN, label: "" },
    reserved_area: { w: 160, h: 72, color: "#c9b8a0", label: "Reserved" },
    church_pew: { w: 240, h: 28, color: WOOD, label: "Pew" },
    outdoor_tent: { w: 280, h: 180, color: "#fef3c7", label: "Tent" },
    garden_arbor: { w: 120, h: 96, color: "#86efac", label: "Arbor" },
    text_label: { w: 200, h: 28, color: "#38bdf8", label: "Label" },
  };
  const d = defaults[type];
  return {
    type,
    x: 120,
    y: 120,
    width: d.w,
    height: d.h,
    rotation: 0,
    label: d.label,
    color: d.color,
    meta:
      type === "round_table" || type === "rectangular_table"
        ? { seatCount: 8, guestNames: [] }
        : type === "sweetheart_table"
          ? { seatCount: 2, guestNames: [] }
          : {},
  };
}
